import java.util.Objects;

// TODO make Quad immutable
// TODO add x,y coordinates to Quad
// TODO make Picture which can draw many Quads
// TODO make Circle and add to Picture
// TODO make Shape which is implemented by Circle and Quad
// TODO spin out drawing into a Drawable interface

public class Quad {

    private double side;
    private double area;

    public Quad() {}

    public Quad(double length) {
        this.side = length;
        this.area = length * length;
    }

    /**
     * Returns the length of the sides of the Quad
     * @return The length of the side of the Quad
     */
    public double getSide() {
        return side;
    }

    /**
     * Sets the value of the sides of the Quad
     * @param side The length of the side
     */
    public void setSide(double side) {
        this.side = side;
        this.area = side * side;
    }

    /**
     * Returns the area of the Quad
     * @return the area of the Quad
     */
    public double area() {
        return this.area;
    }

    /**
     * Returns the perimeter of the Quad
     * @return the perimeter of the Quad
     */
    public double perimeter() {
        return 4 * this.side;
    }

    @Override
    public boolean equals(Object o) {
        // this method is generated by IntelliJ!
        // right-click -> Generate... -> equals() and hashCode()
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Quad quad = (Quad) o;
        return Double.compare(quad.side, side) == 0;
    }

    @Override
    public int hashCode() {
        // this method is generated by IntelliJ!
        // right-click -> Generate... -> equals() and hashCode()
        return Objects.hash(side);
    }

    public String toString() {
        return "Quad with side length " + this.side;
    }

    public static void main(String[] args) {
        Quad square = new Quad();
        StdOut.println(square.toString());
    }

}
